"""
Markdown Formatter

Generates Markdown documents from search results.
Single Responsibility: Only handles Markdown formatting.
"""

from datetime import datetime
from typing import Any, Dict, List


class MarkdownFormatter:
    """Formats search results as Markdown documents."""

    @staticmethod
    def format(
        result: Dict[str, Any],
        include_sources: bool = True,
        include_context: bool = False,
    ) -> str:
        """
        Format search result as Markdown document.

        Args:
            result: Search result from pipeline
            include_sources: Include source links
            include_context: Include full context passages

        Returns:
            Markdown formatted string
        """
        lines: List[str] = []

        # Title
        query = result.get("question", "Search Result")
        lines.append(f"# {query}")
        lines.append("")

        # Metadata
        confidence = result.get("confidence", 0)
        cached = result.get("cached", False)
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        lines.append(f"> **Confidence:** {confidence:.0%} | **Generated:** {timestamp}")
        if cached:
            lines.append("> *Cached result*")
        lines.append("")

        # Answer
        lines.append("## Answer")
        lines.append("")
        lines.append(result.get("answer", "No answer available."))
        lines.append("")

        # Sources
        if include_sources:
            lines.extend(MarkdownFormatter._format_sources(result))

        # Context
        if include_context:
            lines.extend(MarkdownFormatter._format_context(result))

        # Footer
        lines.append("---")
        lines.append("*Generated by SearchFlow*")

        return "\n".join(lines)

    @staticmethod
    def _format_sources(result: Dict[str, Any]) -> List[str]:
        """Format sources section."""
        lines: List[str] = []
        sources = result.get("sources", [])

        if sources:
            lines.append("## Sources")
            lines.append("")
            for i, source in enumerate(sources, 1):
                if isinstance(source, str):
                    lines.append(f"{i}. [{source}]({source})")
                elif isinstance(source, dict):
                    url = source.get("url", "")
                    title = source.get("title", url)
                    lines.append(f"{i}. [{title}]({url})")
            lines.append("")

        return lines

    @staticmethod
    def _format_context(result: Dict[str, Any]) -> List[str]:
        """Format context passages section."""
        lines: List[str] = []
        context = result.get("context", [])

        if context:
            lines.append("## Context Passages")
            lines.append("")
            for i, ctx in enumerate(context, 1):
                if isinstance(ctx, dict):
                    title = ctx.get("title", f"Passage {i}")
                    text = ctx.get("text", "")[:500]
                    url = ctx.get("url", "")
                    lines.append(f"### {title}")
                    if url:
                        lines.append(f"*Source: [{url}]({url})*")
                    lines.append("")
                    lines.append(f"> {text}")
                    lines.append("")

        return lines


def format_as_markdown(result: Dict[str, Any]) -> str:
    """Convenience function for Markdown formatting."""
    return MarkdownFormatter.format(result)
